# Olist E-Commerce Data Cleaning & Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()

'/home/27d84395-bab9-49db-9aa9-3d3a50855c0d'

In [3]:
os.listdir()

['Untitled7.ipynb',
 'Untitled6.ipynb',
 'Cleaned_reviews',
 'Cleaned_customers',
 'Untitled2.ipynb',
 'archive (4).zip',
 '.bashrc',
 'Untitled4.ipynb',
 '.local',
 '.jupyter',
 'Untitled3.ipynb',
 '.vimrc',
 'Untitled.ipynb',
 '.anaconda',
 '.ipynb_checkpoints',
 '.gitconfig',
 'Untitled1.ipynb',
 'Cleaned_products',
 '.virtualenvs',
 'Untitled8.ipynb',
 'Cleaned_sellers',
 '.npm',
 'Untitled5.ipynb',
 'Online_Cusotmer.csv',
 'online_customer.csv',
 'README.ipynb',
 'Cleaned_order_items',
 '.conda',
 '.profile',
 'Cleaned_orders',
 'anaconda_projects',
 'E-commerce Customer Behavior.csv',
 '.ipython',
 'E-Commerce Public Dataset by Olist',
 'Cleaned_payments',
 '.pythonstartup.py']

In [5]:
import os
os.listdir()

['Untitled7.ipynb',
 'Untitled6.ipynb',
 'Cleaned_reviews',
 'Cleaned_customers',
 'Untitled2.ipynb',
 'archive (4).zip',
 '.bashrc',
 'Untitled4.ipynb',
 '.local',
 '.jupyter',
 'Untitled3.ipynb',
 '.vimrc',
 'Untitled.ipynb',
 '.anaconda',
 '.ipynb_checkpoints',
 '.gitconfig',
 'Untitled1.ipynb',
 'Cleaned_products',
 '.virtualenvs',
 'Untitled8.ipynb',
 'Cleaned_sellers',
 '.npm',
 'Untitled5.ipynb',
 'Online_Cusotmer.csv',
 'online_customer.csv',
 'README.ipynb',
 'Cleaned_order_items',
 '.conda',
 '.profile',
 'Cleaned_orders',
 'anaconda_projects',
 'E-commerce Customer Behavior.csv',
 '.ipython',
 'E-Commerce Public Dataset by Olist',
 'Cleaned_payments',
 '.pythonstartup.py']

In [6]:
import zipfile
import os

In [7]:
with zipfile.ZipFile('archive (4).zip','r') as zip_ref:
 zip_ref.extractall('E-Commerce Public Dataset by Olist')

In [8]:
os.listdir('E-Commerce Public Dataset by Olist')

['product_category_name_translation.csv',
 'olist_order_reviews_dataset.csv',
 '.ipynb_checkpoints',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_customers_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv']

In [9]:
df_orders = pd.read_csv("E-Commerce Public Dataset by Olist/olist_orders_dataset.csv")
df_customers = pd.read_csv("E-Commerce Public Dataset by Olist/olist_customers_dataset.csv")
df_order_items = pd.read_csv("E-Commerce Public Dataset by Olist/olist_order_items_dataset.csv")
df_payments = pd.read_csv("E-Commerce Public Dataset by Olist/olist_order_payments_dataset.csv")
df_reviews = pd.read_csv("E-Commerce Public Dataset by Olist/olist_order_reviews_dataset.csv")
df_products = pd.read_csv("E-Commerce Public Dataset by Olist/olist_products_dataset.csv")
df_sellers = pd.read_csv("E-Commerce Public Dataset by Olist/olist_sellers_dataset.csv")
df_geo = pd.read_csv("E-Commerce Public Dataset by Olist/olist_geolocation_dataset.csv")
df_category = pd.read_csv("E-Commerce Public Dataset by Olist/product_category_name_translation.csv")

In [10]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [11]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [12]:
df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [13]:
df_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [14]:
df_orders.duplicated().sum()

0

In [15]:
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
    
]

for col in date_cols:
    df_orders[col] = pd.to_datetime(df_orders[col], errors='coerce')

In [85]:
df_orders[df_orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [87]:
delivered_orders = df_orders[
    df_orders['order_status'] == 'delivered'
].copy()


delivered_orders.shape

(96478, 8)

In [86]:
delivered_orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_days                    0
delivery_delay_days              0
dtype: int64

In [19]:
delivered_orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [20]:
delivered_orders = delivered_orders.dropna(
    subset=[
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date',
    ]
)
delivered_orders.shape

(96455, 8)

In [21]:
delivered_orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [22]:
delivered_orders['delivery_days'] = (
    delivered_orders['order_delivered_customer_date']
    - delivered_orders['order_purchase_timestamp']).dt.days

In [23]:
delivered_orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
delivery_days                             int64
dtype: object

In [24]:
delivered_orders['delivery_delay_days'] = (
    delivered_orders['order_delivered_customer_date']- delivered_orders['order_estimated_delivery_date']
).dt.days

In [25]:
delivered_orders.to_csv('Cleaned_orders',index= False)

In [26]:
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [27]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [28]:
df_customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [29]:
df_customers.duplicated().sum()

0

In [30]:
df_customers.shape

(99441, 5)

In [31]:
df_customers.to_csv('Cleaned_customers',index = False)

In [32]:
df_order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [33]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [34]:
df_order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [35]:
df_order_items.duplicated().sum()

0

In [36]:
df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'],errors = 'coerce')

In [37]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [38]:
df_order_items.to_csv('Cleaned_order_items',index = False)

In [39]:
df_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [40]:
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [41]:
df_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [42]:
df_payments.duplicated().sum()

0

In [43]:
df_payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [44]:
df_payments.to_csv('Cleaned_payments', index=False)

In [45]:
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [46]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [47]:
df_products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [48]:
df_products.shape

(32951, 9)

In [49]:
num_cols = [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm',
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty'
]

for col in num_cols:
    df_products[col] = df_products[col].fillna(df_products[col].median())

In [50]:
df_products['product_category_name'] = df_products['product_category_name'].fillna('unknown')

In [51]:
df_products.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [52]:
df_products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [53]:
df_products.to_csv('Cleaned_products',index = False)

In [54]:
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [55]:
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [56]:
df_sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [57]:
df_sellers.duplicated().sum()

0

In [58]:
df_sellers.to_csv('Cleaned_sellers', index=False)

In [59]:
df_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [60]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [61]:
df_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [62]:
df_reviews['review_score'].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

In [63]:
df_reviews['review_comment_title'] = df_reviews['review_comment_title'].fillna('No Title')
df_reviews['review_comment_message'] = df_reviews['review_comment_message'].fillna('No Comment')

In [64]:
df_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [65]:
df_reviews.duplicated().sum()

0

In [66]:
df_reviews.to_csv('Cleaned_reviews', index=False)

In [67]:
df_geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [68]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [69]:
df_geo.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [70]:
df_geo.duplicated().sum()

261831

In [71]:
df_geo['geolocation_zip_code_prefix'].nunique()

19015

In [102]:
df_geo.shape

(1000163, 5)

In [72]:
df_geo.groupby('geolocation_zip_code_prefix')[
    ['geolocation_city', 'geolocation_state']
].nunique().sort_values(
    by=['geolocation_city', 'geolocation_state'],
    ascending=False
).head(10)

                             geolocation_city  geolocation_state
geolocation_zip_code_prefix
6900                                        5                  1
13318                                       5                  1
13454                                       5                  1
13455                                       5                  1
13457                                       5                  1
17970                                       5                  1
28950                                       5                  1
42850                                       5                  1
78290                                       5                  1
9780                                        4                  1

In [73]:
df_geo[df_geo['geolocation_zip_code_prefix'] == 6900]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
177377,6900,-23.828522,-46.814796,embu-guacu,SP
177378,6900,-23.881320,-46.792154,embu-guacu,SP
177379,6900,-23.827919,-46.814055,embu-guaçu,SP
177380,6900,-23.838855,-46.819628,embu-guacu,SP
177381,6900,-23.838180,-46.820156,embu-guacu,SP
...,...,...,...,...,...
178013,6900,-23.918790,-46.838383,embu-guacu,SP
178014,6900,-23.833916,-46.816282,embu-guacu,SP
178016,6900,-23.833866,-46.811641,embu guaçu,SP
178017,6900,-23.825545,-46.794900,embu-guacu,SP
178018,6900,-23.841988,-46.794238,embu-guacu,SP

In [74]:
df_geo[df_geo['geolocation_zip_code_prefix'] == 6900]['geolocation_city'].value_counts()

geolocation_city
embu-guacu    369
embu-guaçu     46
embu guaçu     21
embu guacu      7
embuguacu       4
Name: count, dtype: int64

In [77]:
df_cleaned_geo = df_geo.drop_duplicates(subset = ['geolocation_zip_code_prefix'])

In [78]:
df_cleaned_geo.to_csv('Cleaned_geo',index = False)

In [79]:
df_category.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [80]:
df_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [81]:
df_category.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [83]:
df_category.duplicated().sum()

0

In [84]:
df_category.to_csv('Cleaned_category',index = False)

In [88]:
import os
os.getcwd()

'/home/27d84395-bab9-49db-9aa9-3d3a50855c0d'

In [89]:
import os

os.listdir()

['Untitled6.ipynb',
 'Cleaned_reviews',
 'Cleaned_customers',
 'Untitled2.ipynb',
 'archive (4).zip',
 '.bashrc',
 'Untitled4.ipynb',
 '.local',
 '.jupyter',
 'Untitled3.ipynb',
 '.vimrc',
 'Untitled.ipynb',
 '.anaconda',
 '.ipynb_checkpoints',
 '.gitconfig',
 'Untitled1.ipynb',
 'Cleaned_products',
 '.virtualenvs',
 'Cleaned_sellers',
 '.npm',
 'Untitled5.ipynb',
 'Online_Cusotmer.csv',
 'online_customer.csv',
 'README.ipynb',
 'Cleaned_geo',
 'Cleaned_order_items',
 '.conda',
 '.profile',
 'Cleaned_orders',
 'anaconda_projects',
 'E-commerce Customer Behavior.csv',
 '.ipython',
 'E-Commerce Public Dataset by Olist',
 'Cleaned_payments',
 'Cleaned_category',
 '.pythonstartup.py']

In [91]:
df_orders.to_csv('Cleaned_orders.csv', index=False)
df_customers.to_csv('Cleaned_customers.csv', index=False)
df_order_items.to_csv('Cleaned_order_items.csv', index=False)
df_payments.to_csv('Cleaned_payments.csv', index=False)
df_products.to_csv('Cleaned_products.csv', index=False)
df_sellers.to_csv('Cleaned_sellers.csv', index=False)
df_reviews.to_csv('Cleaned_reviews.csv', index=False)
df_cleaned_geo.to_csv('Cleaned_geolocation.csv', index=False)
df_category.to_csv('Cleaned_category_translation.csv', index=False)

In [92]:
df_reviews.shape

(99224, 7)

In [93]:
df_reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [100]:
df_reviews[df_reviews['review_comment_message'].astype(str).str.contains('\n', regex=False)].shape

(0, 7)

In [95]:
df_reviews['review_comment_message'] = (
    df_reviews['review_comment_message']
    .str.replace('\n', ' ', regex=False)
)

df_reviews['review_comment_title'] = (
    df_reviews['review_comment_title']
    .str.replace('\n', ' ', regex=False)
)

In [96]:
df_reviews[df_reviews['review_comment_message'].astype(str).str.contains('\n', regex=False)].shape

(0, 7)

In [98]:
df_reviews.to_csv(
    'Cleaned_reviews_fixed.csv',
    index=False,
    quoting=1
)

In [101]:
df_reviews[df_reviews['review_comment_title'].astype(str).str.contains('\n', regex=False)].shape

(0, 7)

In [102]:
df_reviews['review_comment_message'] = (
    df_reviews['review_comment_message']
    .astype(str)
    .str.replace('"', "'", regex=False)
)

df_reviews['review_comment_title'] = (
    df_reviews['review_comment_title']
    .astype(str)
    .str.replace('"', "'", regex=False)
)

In [103]:
import csv

df_reviews.to_csv(
    'Cleaned_reviews.csv',
    index=False,
    quoting=csv.QUOTE_ALL
)

In [106]:
with open('Cleaned_reviews.csv', 'r', encoding='utf-8') as f:
    for i in range(20):
        print(i+1, f.readline())

1 "review_id","order_id","review_score","review_comment_title","review_comment_message","review_creation_date","review_answer_timestamp"

2 "7bc2406110b926393aa56f80a40eba40","73fc7af87114b39712e6da79b0a377eb","4","No Title","No Comment","2018-01-18 00:00:00","2018-01-18 21:46:59"

3 "80e641a11e56f04c1ad469d5645fdfde","a548910a1c6147796b98fdf73dbeba33","5","No Title","No Comment","2018-03-10 00:00:00","2018-03-11 03:05:13"

4 "228ce5500dc1d8e020d8d1322874b6f0","f9e4b658b201a9f2ecdecbb34bed034b","5","No Title","No Comment","2018-02-17 00:00:00","2018-02-18 14:36:24"

5 "e64fb393e7b32834bb789ff8bb30750e","658677c97b385a9be170737859d3511b","5","No Title","Recebi bem antes do prazo estipulado.","2017-04-21 00:00:00","2017-04-21 22:02:06"

6 "f7c4243c7fe1938f181bec41a392bdeb","8e6bfb81e283fa7e4f11123a3fb894f1","5","No Title","Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa","2018-03-01 00:00:00","2018-03-02 10:26:53"

7 "15197aa66ff4d0650b5434f1b46cda19","b18dcdf73be66366873cd26c5724d1dc","1","No Title","No Comment","2018-04-13 00:00:00","2018-04-16 00:39:37"

8 "07f9bee5d1b850860defd761afa7ff16","e48aa0d2dcec3a2e87348811bcfdf22b","5","No Title","No Comment","2017-07-16 00:00:00","2017-07-18 19:30:34"

9 "7c6400515c67679fbee952a7525281ef","c31a859e34e3adac22f376954e19b39d","5","No Title","No Comment","2018-08-14 00:00:00","2018-08-14 21:36:06"

10 "a3f6f7f6f433de0aefbb97da197c554c","9c214ac970e84273583ab523dfafd09b","5","No Title","No Comment","2017-05-17 00:00:00","2017-05-18 12:05:37"

11 "8670d52e15e00043ae7de4c01cc2fe06","b9bf720beb4ab3728760088589c62129","4","recomendo","aparelho eficiente. no site a marca do aparelho esta impresso como 3desinfector e ao chegar esta com outro nome...atualizar com a marca correta uma vez que é o mesmo aparelho","2018-05-22 00:00:00","2018-05-23 16:45:47"

12 "c9cfd2d5ab5911836ababae136c3a10c","cdf9aa68e72324eeb25c7de974696ee2","5","No Title","No Comment","2017-12-23 00:00:00","2017-12-26 14:36:03"

13 "96052551d87e5f62e6c9f6974ec392e9","3d374c9e46530bb5ed4a7648915306a6","5","No Title","No Comment","2017-12-19 00:00:00","2017-12-20 10:25:22"

14 "4b49719c8a200003f700d3d986ea1a19","9d6f15f95d01e79bd1349cc208361f09","4","No Title","Mas um pouco ,travando...pelo valor ta Boa.

15  ","2018-02-16 00:00:00","2018-02-20 10:52:22"

16 "23f75a37effc35d9a915b4e1ad483793","2eaf8e099d871cd5c22b83b5ea8f6e0e","4","No Title","No Comment","2018-03-28 00:00:00","2018-03-30 15:10:55"

17 "9a0abbb668bafb95a6d2b05db43284c4","d7bd0e4afdf94846eb73642b4e3e75c3","3","No Title","No Comment","2017-04-30 00:00:00","2017-05-03 00:02:22"

18 "3948b09f7c818e2d86c9a546758b2335","e51478e7e277a83743b6f9991dbfa3fb","5","Super recomendo","Vendedor confiável, produto ok e entrega antes do prazo.","2018-05-23 00:00:00","2018-05-24 03:00:01"

19 "9314d6f9799f5bfba510cc7bcd468c01","0dacf04c5ad59fd5a0cc1faa07c34e39","2","No Title","GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E ESSA COMPRA AGORA ME DECPCIONOU","2018-01-18 00:00:00","2018-01-20 21:25:45"

20 "8e15a274d95600fa14f8be64e37a0e67","ff1581e08b3011021e7c7de592ddc81e","5","No Title","No Comment","2018-03-24 00:00:00","2018-03-26 15:58:32"

In [107]:
import csv

# Convert to string and remove problematic quotes
for col in ['review_comment_title', 'review_comment_message']:
    df_reviews[col] = (
        df_reviews[col]
        .fillna('No comment')
        .astype(str)
        .str.replace('"', '', regex=False)
        .str.replace('\n', ' ', regex=False)
        .str.replace('\r', ' ', regex=False)
    )

df_reviews.to_csv(
    'Cleaned_reviews_final.csv',
    index=False,
    quoting=csv.QUOTE_ALL
)

In [108]:
import csv

with open('Cleaned_reviews_final.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    for i, row in enumerate(reader):
        if len(row) != 7:
            print("Problem row:", i+1, len(row))
            break